### ISSUE TITLE
Issues for next sprint

### ISSUE THREAD

**Issue by slamsy** [slamsy/flask-cat-lives#13]
- ~~Buttons~~
- [DEFERRED] Input style (mobile keyboard) (mccooll)
- [DEFERRED] The spaces running onto new lines 
- ~~Logo / favicon~~ (slamsy)
- ~~Font style and size~~ (slamsy)
- ~~Wrong letters on dead cats~~ (mccooll)
- [DEFERRED] Mobile behaviour (mccooll)
- ~~Colours~~ (slamsy)
- ~~Instructions~~ (slamsy/mccooll)
- [DEFERRED] Victory screens?

**Comment by mccooll** [comment]
~~helvetica, verdana, calibri, ubuntu~~

**Comment by mccooll** [comment]
size: ~2/3 on desktop, 1/2 on mobile for blanks; buttons 1/2 of blanks (except maybe bigger if needed on mobile)

**Comment by mccooll** [comment]
switch to mobile view

**Comment by mccooll** [comment]
@slamsy need to trim image

**Comment by mccooll** [comment]
consider changing black glow to pink

**Comment by mccooll** [comment]
fix disastrous wrong letters

**Comment by mccooll** [comment]
add animation to wrong letter
