### ISSUE TITLE
Setup Google Cloud CD

### ISSUE THREAD

**Issue by mccooll** [slamsy/flask-cat-lives#15]
Automatically deploy master updates to GCP.

Ideas:
https://github.com/marketplace/google-cloud-build
https://cloud.google.com/cloud-build/docs/automating-builds/run-builds-on-github

**Comment by slamsy** [comment]
Instructions for Mac OS https://cloud.google.com/sdk/docs/quickstart-macos
SDK package and deploy commands https://console.cloud.google.com/appengine/start/deploy?language=python&environment=standard&project=robust-shadow-281000&folder&organizationId&pli=1

**Comment by mccooll** [comment]
Status: tried to setup an action which is merged to master but I don't think it's properly configured or running.

**Comment by mccooll** [comment]
was in wrong folder. added pull request for review. @slamsy did you want to move your comment? I was thinking of closing #29 as well. But maybe you feel we will still need some documentation.
